# This config file is meant for settings that affect the whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shonan Rotation Averaging
email: dellaert@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Shonan Rotation Averaging is a fast, simple, and elegant rotation averaging algorithm that is guaranteed to recover globally optimal solutions under mild assumptions on the measurement noise.
url: "https://dellaert.github.io/ShonanAveraging" # the base hostname & protocol for your site
twitter_username: fdellaert
github_username:  dellaert

# Build settings
markdown: kramdown

header_pages:
  - index.md
  # - news.md

exclude: ['node_modules', 'src']
